require "main.scripts.loop_test"

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then 
		local button = gui.get_node("button") 
		local text = gui.get_node("text") 
		local results = "running test"
		if gui.pick_node(button, action.x, action.y) then 
			local results = run_test()
			label.set_text("/go#label", results)
		end
	end
end